exp_name: "basic_ppo_4w_b2b_combo"
seed: 42

net_arch:  [128]
features_per_placement: 4
learning_rate: 0.0001
lr_end: 0.00001
clip_range: 0.1
rollout_samples: 25000
batch_size: 256
ent_coef: 0.005
ent_coef_end: 0.001
gamma: 0.99
n_envs: 4
verbose: 0

eval_interval_samples: 100000
eval_episodes: 100
max_eval_pieces: 1000
curriculum_learned_ratio: 0.5
total_timesteps: 5000000

clear_lines_on_placement: true
use_heuristic_rewards: true

board_w: 6
