exp_name: "basic_tetrio"
seed: 42

features_per_placement: 1

learning_rate: 0.0001
tetrio_epochs: 100
patience: 10
label_smoothing: 0.1
weight_decay: 0.0001
eta_min: 0.00001
batch_size: 192
num_workers: 12

wide_k: 2
channels: 24

clear_lines_on_placement: true
