# Heuristic and survival rewards seem to work!
exp_name: "config_curr_ppo"
seed: 42

net_arch:  [156]
features_per_placement: 1
learning_rate: 0.0002
clip_range: 0.1
rollout_samples: 73728
batch_size: 256
n_epochs: 10
ent_coef: 0.005
gamma: 0.9995
gae_lambda: 0.98
n_envs: 12
verbose: 0

wide_k: 4
channels: 32

eval_every_rollouts: 3
eval_episodes: 100
max_eval_pieces: 500
run_final_eval: false
curriculum_learned_ratio: 0.9

# total_timesteps: 5000000

clear_lines_on_placement: true
target_kl: 0.015

curriculum:
  4: 10000000
  6: 10000000
  8: 10000000
  10: 10000000
  -1: 5000000

random_width:
  4: 0.05
  6: 0.05
  8: 0.05
  10: 0.85

garbage_prob: 0.0

use_survival_rewards: True
use_heuristic_rewards: True
use_game_rewards: False
alive_reward: 0.1
death_penalty: -5.0

heuristic_reward_scale: 0.01
heuristic_reward_cap: 0.1
line_clear_rewards:
  1: 1.0
  2: 2.0
  3: 3.0
  4: 6.0
t_spin_rewards:
  1: 2.0
  2: 6.0
  3: 9.0
all_clear_reward: 20.0
combo_reward_multiplier: 1.25

# CAMBIAR QUITAR UNA RESIDUAL
# CAMBIAR METER EL PIECES TO BOARD ATTENTION
