exp_name: "basic_ppo"
seed: 42

net_arch:  [128]
features_per_placement: 1
learning_rate: 0.0001
lr_end: 0.00001
clip_range: 0.1
n_steps: 2048
batch_size: 256
ent_coef: 0.005
ent_coef_end: 0.001
gamma: 0.99
n_envs: 4
verbose: 0

save_freq: 50000

total_timesteps: 5000000

clear_lines_on_placement: true
use_heuristic_rewards: true